name: Static Code Review

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          coverage: none
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install PHP Dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist

      - name: Set up Laravel environment
        run: |
          cp .env.example .env
          php artisan key:generate
          mkdir -p bootstrap/cache storage/framework/{views,cache}
          chmod -R 755 bootstrap storage

      - name: Run migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test



      # ---------- Laravel Pint (code style) ----------
      - name: Run Laravel Pint
        run: |
          vendor/bin/pint --test

      # ---------- PHPStan / Larastan ----------
      - name: Run PHPStan (Larastan)
        run: |
          vendor/bin/phpstan analyse --configuration=phpstan.neon
